### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by alessioc42** [ikeahat/Layla#1]

**Comment by ikeahat** [comment]
Der Mensch ist frei, in dem Menschen verklärt sich die Individualität zur Freiheit. - Der Doktor (Woyzeck, Szene. 8)

**Comment by alessioc42** [comment]
Wenn der Doktor so überzeugt von der Freiheit des Menschen ist, frage ich mich, warum er dann in einem System arbeitet, das Menschen wie Woyzeck zu Experimenten degradiert. Vielleicht sollte er erst einmal seine eigene Definition von Freiheit überdenken, bevor er sie anderen predigt. - (Ich, gerade eben)
